<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="725" started-at="2022-09-30T17:23:32 IST" finished-at="2022-09-30T17:23:33 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="725" started-at="2022-09-30T17:23:32 IST" finished-at="2022-09-30T17:23:33 IST">
      <class name="com.Testng_Attributes.Attributes_Demo">
        <test-method status="PASS" signature="Amazon()[pri:-1, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="Amazon" duration-ms="124" started-at="2022-09-30T17:23:32 IST" finished-at="2022-09-30T17:23:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amazon -->
        <test-method status="PASS" signature="Amazon()[pri:-1, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="Amazon" duration-ms="23" started-at="2022-09-30T17:23:33 IST" finished-at="2022-09-30T17:23:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Amazon -->
        <test-method status="PASS" signature="BigBasket()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="BigBasket" duration-ms="18" started-at="2022-09-30T17:23:33 IST" finished-at="2022-09-30T17:23:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BigBasket -->
        <test-method status="PASS" signature="India()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="India" duration-ms="18" started-at="2022-09-30T17:23:33 IST" description="Hello" finished-at="2022-09-30T17:23:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- India -->
        <test-method status="FAIL" signature="Myntra()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="Myntra" duration-ms="13" started-at="2022-09-30T17:23:33 IST" finished-at="2022-09-30T17:23:33 IST">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at com.Testng_Attributes.Attributes_Demo.Myntra(Attributes_Demo.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Myntra -->
        <test-method status="PASS" signature="meesho()[pri:-4, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="meesho" duration-ms="19" started-at="2022-09-30T17:23:33 IST" depends-on-methods="com.Testng_Attributes.Attributes_Demo.Myntra" finished-at="2022-09-30T17:23:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- meesho -->
        <test-method status="FAIL" signature="TataSky()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1]" name="TataSky" duration-ms="10" started-at="2022-09-30T17:23:33 IST" finished-at="2022-09-30T17:23:33 IST">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method Attributes_Demo.TataSky()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method Attributes_Demo.TataSky()[pri:0, instance:com.Testng_Attributes.Attributes_Demo@635eaaf1] should have thrown an exception of type class java.lang.ArithmeticException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TataSky -->
      </class> <!-- com.Testng_Attributes.Attributes_Demo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
